In [ ]:
# What are gonna study in this section: 


# Merging two(2) data frames 
# Concatenation of two(2) of data frames 
# Joining of two(2) data frames

In [2]:
import numpy as np 
import pandas as pd

In [6]:
# data frames for working: 

employees = pd.DataFrame({
    'employee_id': [1 , 2 , 3 , 4 , 5], 
    'name': ['John' , 'Anna' , 'Peter' , 'Linda' , 'Bob'],
    'department': ['HR' , 'IT' , 'Finance' , 'IT' , 'HR']
})

# Data Frame two for salary information: 

salaries = pd.DataFrame({
    'employee_id': [1 , 2 , 3 , 6 , 7],
    'salary': [60000 , 80000 , 65000 , 70000 , 90000],
    'bonus': [5000 , 10000 , 7000 , 8000 , 12000]
})

In [7]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [21]:
employees

# Now if you want to merge two(2) data frames then do it

mergedId = pd.merge(employees, salaries, on="employee_id", how="outer")

# how="outer"
# It keeps ALL rows from BOTH DataFrames (employees + salaries).
# If employee_id matches in both tables → rows are merged.
# If employee_id exists in only one table → still kept, but missing values become NaN.
# Basically it performs a FULL OUTER JOIN (union of both tables).

mergedId = pd.merge(employees , salaries , on="employee_id" , how="left")
mergedId

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [31]:
# Concatenation of two data frames:

# data: 

df1 = pd.DataFrame({
    'A': ['A0' , 'A1' , 'A2'],
    'B': ['B0' , 'B1' , 'B2'],
    'C': ['C0' , 'C1' , 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3' , 'A4' , 'A5'], 
    'B': ['B3' , 'B4' , 'B5'] ,
    'C': ['C3' , 'C4' , 'C5']
})

In [34]:
# Concatenation according to columns

pd.concat([df1 , df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [35]:
# concatenation according to rows

pd.concat([df1 , df2] , axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [42]:
# **Joining of two(2) data frames


# data 
df1 = pd.DataFrame({
    'name': ["Alice" , "Bob" , "Charlie"]
} , index=[1,2,3])

df2 = pd.DataFrame({
    'score': [85 , 90 , 75]
} , index=[2,3,4])

In [45]:
df1.join(df2 , how="outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0