In [ ]:
# Operations in pandas:

# Operations in pandas are the tasks or actions performed on DataFrames and Series to manipulate,
# analyze, organize, transform, and summarize data.

# Operations = things we do with data in pandas

In [3]:
import numpy as np 
import pandas as pd

In [4]:
# Data frame basic operations:  

df1 = pd.DataFrame({
    'A': [1,2,3,4,5] , 
    'B': [10,20,30,40,50] , 
    'C': [100,200,300,400,500]
})

df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [5]:
# This will tell that how many row and columns are there , first value is for columns and the second value is for columns. 

df1.shape

(5, 3)

In [6]:
# This will give the exact value of elements present inside rows and columns of a data frame.

df1.size

15

In [7]:
# This will give you the names of each column sequencly.  

df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [10]:
# This will give the info of all the data frame. 

df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [11]:
# If you want the mathematical description of your data frame then do this.

df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [12]:
# We can also do the broadcasting in the data frame column like this. 

df1["A"] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
# DataFrames Applying Functions:

In [15]:
# My code: 

eachAelem = df1["B"]

def square() :
    for i in eachAelem : 
        print(i * i)

square()

100
400
900
1600
2500

In [27]:
# Teacher's code: 

def square(x) : 
    return x ** 2

df1['D'] = df1['B'].apply(square)

In [28]:
df1

,A,B,C,D
0,1,100000000000000000000000000000000,100,1000000000000000000000000000000000000000000000...
1,2,429496729600000000000000000000000000000000,200,1844674407370955161600000000000000000000000000...
2,3,185302018885184100000000000000000000000000000000,300,3433683820292512484657849089281000000000000000...
3,4,1844674407370955161600000000000000000000000000...,400,3402823669209384634633746074317682114560000000...
4,5,2328306436538696289062500000000000000000000000...,500,5421010862427522170037264004349708557128906250...

In [ ]:
# more easy way: 

df1['D'] = df1['B'].apply