In [ ]:
# Pivot tables: 

# A pivot table is a data summarization tool used to organize, group, and aggregate data in a tabular format. 
# It helps analyze data by rearranging rows and columns and applying functions like sum, mean, count, min, or max.
# Pivot table = summarize large data into an easy report

In [4]:
import pandas as pd 
import numpy as np

In [9]:
# data: 

data = {
    'Date': pd.date_range('2023-01-01' , periods=20) ,
    'Product': ['A','B','C','D'] * 5, 
    'Region': ['East','West','North','South','East','West','North','South','East','West','North','South',
              'East','West','North','South','East','West','North','South'], 
    'Sales': np.random.randint(100,1000,20),
    'Units': np.random.randint(10,100,20),
    'Rep': ['John' , 'Mary' , 'Bob' , 'Alice', 'John' , 'Mary' , 'Bob' , 'Alice', 
           'John' , 'Mary' , 'Bob' , 'Alice', 'John' , 'Mary' , 'Bob' , 'Alice',
           'John' , 'Mary' , 'Bob' , 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str) 

df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    998     39   John  January      Q1
1  2023-01-02       B   West    275     84   Mary  January      Q1
2  2023-01-03       C  North    156     21    Bob  January      Q1
3  2023-01-04       D  South    700     94  Alice  January      Q1
4  2023-01-05       A   East    402     38   John  January      Q1
5  2023-01-06       B   West    154     52   Mary  January      Q1
6  2023-01-07       C  North    601     10    Bob  January      Q1
7  2023-01-08       D  South    609     63  Alice  January      Q1
8  2023-01-09       A   East    704     66   John  January      Q1
9  2023-01-10       B   West    209     19   Mary  January      Q1
10 2023-01-11       C  North    920     90    Bob  January      Q1
11 2023-01-12       D  South    153     77  Alice  January      Q1
12 2023-01-13       A   East    525     38   John  January      Q1
13 2023-01-14       B   West    691     81   Mary  January      Q1
14 2023-01-15       C  North    627     45    Bob  January      Q1
15 2023-01-16       D  South    255     48  Alice  January      Q1
16 2023-01-17       A   East    273     94   John  January      Q1
17 2023-01-18       B   West    433     63   Mary  January      Q1
18 2023-01-19       C  North    541     76    Bob  January      Q1
19 2023-01-20       D  South    213     96  Alice  January      Q1

In [10]:
# Example of pivot table: 

pd.pivot_table(df , values="Sales" , index="Region" , columns="Product")

Product      A      B      C      D
Region
East     580.4    NaN    NaN    NaN
North      NaN    NaN  569.0    NaN
South      NaN    NaN    NaN  386.0
West       NaN  352.4    NaN    NaN

In [11]:
pivot2 = pd.pivot_table(df , values=["Sales" , "Units"] , index="Region" , columns="Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     580.4    NaN    NaN    NaN  55.0   NaN   NaN   NaN
North      NaN    NaN  569.0    NaN   NaN   NaN  48.4   NaN
South      NaN    NaN    NaN  386.0   NaN   NaN   NaN  75.6
West       NaN  352.4    NaN    NaN   NaN  59.8   NaN   NaN

In [12]:
# Cross tabs

In [ ]:
# Cross tabs are used for counting purpose inside a data frame column: 

pd.crosstab(df[])