# Importing Basic Libraries

In [426]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Loading DataSet

In [427]:
df: pd.DataFrame = pd.read_csv('Telco_Customers_Churn.csv')

In [428]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

# Base EDA(Exploratory Data Analysis) On DataFrame Structure

In [429]:
df.shape

(7043, 21)

In [430]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [431]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [432]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [433]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Chi Square Test

> We are doing DL, you should know Statistics, Linear Algebra basics, Machine learning & Calculus Basics

> But if you dont know about chi2 test you can visit my statistics dir file https://github.com/Sheharyar-Sarmad/ai-zero-to-hero/blob/main/7_statistics/20_chi_square.md here's the link

In [434]:
from scipy.stats import chi2_contingency

for col in df.select_dtypes(include='object').columns:
    if col == 'Churn':
        continue

    table = pd.crosstab(df[col], df['Churn'])
    chi2, p, dof, expected = chi2_contingency(table)

    print(f'{col}: p-value = {p:.5f}')

customerID: p-value = 0.49440
gender: p-value = 0.48658
Partner: p-value = 0.00000
Dependents: p-value = 0.00000
PhoneService: p-value = 0.33878
MultipleLines: p-value = 0.00346
InternetService: p-value = 0.00000
OnlineSecurity: p-value = 0.00000
OnlineBackup: p-value = 0.00000
DeviceProtection: p-value = 0.00000
TechSupport: p-value = 0.00000
StreamingTV: p-value = 0.00000
StreamingMovies: p-value = 0.00000
Contract: p-value = 0.00000
PaperlessBilling: p-value = 0.00000
PaymentMethod: p-value = 0.00000
TotalCharges: p-value = 0.55325

# Data Cleaning

In [435]:
df_encode = df.copy()

In [436]:
df_encode = df_encode.drop(
    columns=['customerID', 'gender', 'PhoneService'],
    axis=1
) # These are unneccessary features

In [437]:
df_encode['TotalCharges'] = pd.to_numeric(df_encode['TotalCharges'], errors='coerce')

In [438]:
df_encode['TotalCharges'].dtypes

dtype('float64')

In [439]:
df_encode['TotalCharges'].isna().sum()

np.int64(11)

In [440]:
df_encode.dropna(subset=['TotalCharges'], inplace=True)

In [441]:
df_encode['TotalCharges'].isna().sum()

np.int64(0)

In [442]:
df_encode.isnull().sum()

SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# Data Preprocessing

In [443]:
df_encode['SeniorCitizen'].value_counts()

SeniorCitizen
0    5890
1    1142
Name: count, dtype: int64

In [444]:
df_encode.columns

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges',
       'Churn'],
      dtype='object')

In [445]:
df_encode['Partner'].value_counts()

Partner
No     3639
Yes    3393
Name: count, dtype: int64

In [446]:
def binary_classification(
    dataframe: pd.DataFrame,
    column: str,
    val1: str|int|float,
    val2: str|int|float
) -> None:
    dataframe[column] = dataframe[column].map({val1: 1, val2: 0})
    return None

In [447]:
binary_classification(dataframe=df_encode, column='Partner', val1='Yes', val2='No')
df_encode['Partner'].value_counts()

Partner
0    3639
1    3393
Name: count, dtype: int64

In [448]:
df['Dependents'].value_counts()

Dependents
No     4933
Yes    2110
Name: count, dtype: int64

In [449]:
binary_classification(dataframe=df_encode, column='Dependents', val1='Yes', val2='No')
df_encode['Dependents'].value_counts()

Dependents
0    4933
1    2099
Name: count, dtype: int64

In [450]:
df['tenure'].value_counts() # We will apply standard scaler after splitting of data

tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

In [451]:
df_encode.columns

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges',
       'Churn'],
      dtype='object')

In [452]:
df_encode['MultipleLines'].value_counts()

MultipleLines
No                  3385
Yes                 2967
No phone service     680
Name: count, dtype: int64

In [453]:
def map_column(
    dataframe: pd.DataFrame,
    column: str,
    mapping: dict
):
    dataframe[column] = dataframe[column].map(mapping)
    return None

In [454]:
map_column(df_encode, 'MultipleLines', {
    'Yes': 1,
    'No': 0,
    'No phone service': 0
})
df_encode['MultipleLines'].value_counts()

MultipleLines
0    4065
1    2967
Name: count, dtype: int64

In [455]:
df['InternetService'].value_counts()

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

In [456]:
df_encode['Contract'].value_counts()

Contract
Month-to-month    3875
Two year          1685
One year          1472
Name: count, dtype: int64

In [457]:
len(df_encode.columns)

18

In [458]:
# Ordinal for Contract (real order)
df_encode['Contract'] = df_encode['Contract'].map({
    'Month-to-month': 0,
    'One year': 1,
    'Two year': 2
})

# One-hot for the other two
df_encode = pd.get_dummies(
    df_encode,
    columns=['InternetService', 'PaymentMethod'],
    drop_first=True
)

print(df_encode.shape)   # (7032, 21)

(7032, 21)

In [459]:
df_encode.isna().sum()

SeniorCitizen                            0
Partner                                  0
Dependents                               0
tenure                                   0
MultipleLines                            0
OnlineSecurity                           0
OnlineBackup                             0
DeviceProtection                         0
TechSupport                              0
StreamingTV                              0
StreamingMovies                          0
Contract                                 0
PaperlessBilling                         0
MonthlyCharges                           0
TotalCharges                             0
Churn                                    0
InternetService_Fiber optic              0
InternetService_No                       0
PaymentMethod_Credit card (automatic)    0
PaymentMethod_Electronic check           0
PaymentMethod_Mailed check               0
dtype: int64

In [460]:
df_encode.isnull().sum()

SeniorCitizen                            0
Partner                                  0
Dependents                               0
tenure                                   0
MultipleLines                            0
OnlineSecurity                           0
OnlineBackup                             0
DeviceProtection                         0
TechSupport                              0
StreamingTV                              0
StreamingMovies                          0
Contract                                 0
PaperlessBilling                         0
MonthlyCharges                           0
TotalCharges                             0
Churn                                    0
InternetService_Fiber optic              0
InternetService_No                       0
PaymentMethod_Credit card (automatic)    0
PaymentMethod_Electronic check           0
PaymentMethod_Mailed check               0
dtype: int64

In [461]:
df_encode.columns

Index(['SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'MultipleLines',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'MonthlyCharges', 'TotalCharges', 'Churn',
       'InternetService_Fiber optic', 'InternetService_No',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [462]:
print(df_encode.select_dtypes(include='object').columns.tolist())

['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'Churn']

In [463]:
df['OnlineBackup'].value_counts()

OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

In [464]:
map_column(df_encode, 'OnlineBackup', {
    'No': 0,
    'Yes': 1,
    'No internet service': 0
})
df_encode['OnlineBackup'].value_counts()

OnlineBackup
0    4607
1    2425
Name: count, dtype: int64

In [465]:
df['OnlineSecurity'].value_counts()

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

In [466]:
map_column(df_encode, 'OnlineSecurity', {
    'No': 0,
    'Yes': 1,
    'No internet service': 0
})
df_encode['OnlineSecurity'].value_counts()

OnlineSecurity
0    5017
1    2015
Name: count, dtype: int64

In [467]:
df['DeviceProtection'].value_counts()

DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

In [468]:
map_column(df_encode, 'DeviceProtection', {
    'No': 0,
    'Yes': 1,
    'No internet service': 0
})
df_encode['DeviceProtection'].value_counts()

DeviceProtection
0    4614
1    2418
Name: count, dtype: int64

In [469]:
df['TechSupport'].value_counts()

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

In [470]:
map_column(df_encode, 'TechSupport', {
    'No': 0,
    'Yes': 1,
    'No internet service': 0
})
df_encode['TechSupport'].value_counts()

TechSupport
0    4992
1    2040
Name: count, dtype: int64

In [471]:
df['StreamingTV'].value_counts()

StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

In [472]:
map_column(df_encode, 'StreamingTV', {
    'No': 0,
    'Yes': 1,
    'No internet service': 0
})
df_encode['StreamingTV'].value_counts()

StreamingTV
0    4329
1    2703
Name: count, dtype: int64

In [473]:
df['StreamingMovies'].value_counts()

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

In [474]:
map_column(df_encode, 'StreamingMovies', {
    'No': 0,
    'Yes': 1,
    'No internet service': 0
})
df_encode['StreamingMovies'].value_counts()

StreamingMovies
0    4301
1    2731
Name: count, dtype: int64

In [475]:
df['PaperlessBilling'].value_counts()

PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

In [476]:
map_column(df_encode, 'PaperlessBilling', {
    'No': 0,
    'Yes': 1,
})
df_encode['PaperlessBilling'].value_counts()

PaperlessBilling
1    4168
0    2864
Name: count, dtype: int64

In [477]:
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [478]:
map_column(df_encode, 'Churn', {
    'No': 0,
    'Yes': 1,
})
df_encode['Churn'].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [479]:
df_encode.head()

,SeniorCitizen,Partner,Dependents,tenure,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,1,0,0,1,0,0,0,...,0,1,29.85,29.85,0,False,False,False,True,False
1,0,0,0,34,0,1,0,1,0,0,...,1,0,56.95,1889.50,0,False,False,False,False,True
2,0,0,0,2,0,1,1,0,0,0,...,0,1,53.85,108.15,1,False,False,False,False,True
3,0,0,0,45,0,1,0,1,1,0,...,1,0,42.30,1840.75,0,False,False,False,False,False
4,0,0,0,2,0,0,0,0,0,0,...,0,1,70.70,151.65,1,True,False,False,True,False

In [480]:
onehot_cols = [
    'InternetService_Fiber optic',
    'InternetService_No',
    'PaymentMethod_Credit card (automatic)',
    'PaymentMethod_Electronic check',
    'PaymentMethod_Mailed check'
]

In [481]:
for col in onehot_cols:
  df_encode[col] = df_encode[col].astype(int)

# Checking Some Important Details & Creating final_df

In [482]:
df_encode.head()

,SeniorCitizen,Partner,Dependents,tenure,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,1,0,0,1,0,0,0,...,0,1,29.85,29.85,0,0,0,0,1,0
1,0,0,0,34,0,1,0,1,0,0,...,1,0,56.95,1889.50,0,0,0,0,0,1
2,0,0,0,2,0,1,1,0,0,0,...,0,1,53.85,108.15,1,0,0,0,0,1
3,0,0,0,45,0,1,0,1,1,0,...,1,0,42.30,1840.75,0,0,0,0,0,0
4,0,0,0,2,0,0,0,0,0,0,...,0,1,70.70,151.65,1,1,0,0,1,0

In [484]:
df_encode.nunique()

SeniorCitizen                               2
Partner                                     2
Dependents                                  2
tenure                                     72
MultipleLines                               2
OnlineSecurity                              2
OnlineBackup                                2
DeviceProtection                            2
TechSupport                                 2
StreamingTV                                 2
StreamingMovies                             2
Contract                                    3
PaperlessBilling                            2
MonthlyCharges                           1584
TotalCharges                             6530
Churn                                       2
InternetService_Fiber optic                 2
InternetService_No                          2
PaymentMethod_Credit card (automatic)       2
PaymentMethod_Electronic check              2
PaymentMethod_Mailed check                  2
dtype: int64

In [485]:
print("Object cols:", df_encode.select_dtypes('object').columns.tolist())
print("Bool cols:",   df_encode.select_dtypes('bool').columns.tolist())

Object cols: []
Bool cols: []

In [486]:
binary_like = [
    'SeniorCitizen', 'Partner', 'Dependents', 'MultipleLines',
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
    'StreamingTV', 'StreamingMovies', 'PaperlessBilling', 'Churn',
    'InternetService_Fiber optic', 'InternetService_No',
    'PaymentMethod_Credit card (automatic)',
    'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'
]

for col in binary_like:
    vals = sorted(df_encode[col].dropna().unique())
    if vals != [0, 1]:
        print(f"{col}: {vals}")

print("All binary columns OK")

All binary columns OK

In [487]:
print("Total NaNs:", df_encode.isna().sum().sum())
print("NaNs per column:")
print(df_encode.isna().sum()[df_encode.isna().sum() > 0])

Total NaNs: 0
NaNs per column:
Series([], dtype: int64)

In [489]:
df_encode.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   Partner                                7032 non-null   int64
 2   Dependents                             7032 non-null   int64
 3   tenure                                 7032 non-null   int64
 4   MultipleLines                          7032 non-null   int64
 5   OnlineSecurity                         7032 non-null   int64
 6   OnlineBackup                           7032 non-null   int64
 7   DeviceProtection                       7032 non-null   int64
 8   TechSupport                            7032 non-null   int64
 9   StreamingTV                            7032 non-null   int64
 10  StreamingMovies                        7032 non-null   int64
 11  Contract                               7032 non-null   int64
 12  PaperlessBilling                       7032 non-null   int64
 13  MonthlyCharges                         7032 non-null   float64
 14  TotalCharges                           7032 non-null   float64
 15  Churn                                  7032 non-null   int64
 16  InternetService_Fiber optic            7032 non-null   int64
 17  InternetService_No                     7032 non-null   int64
 18  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 19  PaymentMethod_Electronic check         7032 non-null   int64
 20  PaymentMethod_Mailed check             7032 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 1.2 MB

In [490]:
final_df: pd.DataFrame = df_encode.copy() # No Outliers Detected & Data is Fully
# ready for next step, i pick the data hard myself because it required real
# engineering and we will do it, the only way you can learn is to practice and
# making projects

# This project is very low according to industry standards but if you will
# practicing on these kind of little complex data then working on FANG data or
# real world messy data will eventually become easy for you and thats how you
# become real data scientist and ai engineer

In [492]:
final_df.to_csv('Telco_Churn_Final.csv', index=False)
print("Saved")

# Save the final dataset before training and testing if you want
# its not compulsory its optional and note that no standarization or
# normalization is yet performed on this dataset the qualitative variables are
# raw

Saved

# Creating X, y & Performing Train Test Split

In [493]:
X = df_encode.drop(columns='Churn', axis=1)
y = df_encode['Churn']

In [495]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, test_size=0.2, stratify=y
)

# Creating X_train_scaled & X_test_scaled

In [501]:
from sklearn.preprocessing import StandardScaler

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

numeric_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

scaler = StandardScaler()

X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

# Creating Trying Multiple Base Models & Viewing Its Accuracy

In [509]:
# Not good for this problem
from sklearn.linear_model import Perceptron
from sklearn.metrics import classification_report, accuracy_score

perceptron = Perceptron(
    max_iter=1000,
    tol=1e-3,
    random_state=42
)
perceptron.fit(X_train_scaled, y_train)

y_pred = perceptron.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7235252309879175
              precision    recall  f1-score   support

           0       0.89      0.71      0.79      1033
           1       0.49      0.75      0.59       374

    accuracy                           0.72      1407
   macro avg       0.69      0.73      0.69      1407
weighted avg       0.78      0.72      0.74      1407

In [512]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
lr.fit(X_train_scaled, y_train)

y_pred = lr.predict(X_test_scaled)

print(lr.score(X_test_scaled, y_test))
print(classification_report(y_test, y_pred))

0.7263681592039801
              precision    recall  f1-score   support

           0       0.91      0.70      0.79      1033
           1       0.49      0.80      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407

In [513]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42)
rf.fit(X_train, y_train)          # no scaling needed for trees

y_pred = rf.predict(X_test_scaled)

print(rf.score(X_test, y_test))
print(classification_report(y_test, y_pred))

0.7810945273631841
              precision    recall  f1-score   support

           0       0.87      0.77      0.81      1033
           1       0.51      0.67      0.58       374

    accuracy                           0.74      1407
   macro avg       0.69      0.72      0.70      1407
weighted avg       0.77      0.74      0.75      1407

# Creating Final ANN(Aritifical Neural Network) Model

In [516]:
import tensorflow as tf
from tensorflow import keras
from keras import layers
from keras import regularizers
from keras import layers
from keras.layers import Dense, Dropout
from keras.utils import to_categorical

In [517]:
ann_model = keras.Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],)),
    layers.Dense(128, activation='relu',
                 kernel_initializer='he_normal',
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu',
                 kernel_initializer='he_normal',
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.Dropout(0.2),
    layers.Dense(1, activation='sigmoid')
])

In [518]:
ann_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy', keras.metrics.AUC(name='auc')]
)

ann_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         2,688 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,009 (43.00 KB)

 Trainable params: 11,009 (43.00 KB)

 Non-trainable params: 0 (0.00 B)

In [519]:
from sklearn.utils.class_weight import compute_class_weight
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

classes = np.unique(y_train)
weights = compute_class_weight('balanced', classes=classes, y=y_train)
class_weight = dict(zip(classes, weights))

early = EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=4, verbose=1)

history = ann_model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=150,
    batch_size=32,
    class_weight=class_weight,
    callbacks=[early, reduce_lr],
    verbose=1
)

Epoch 1/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.7102 - auc: 0.7951 - loss: 0.5920 - val_accuracy: 0.7680 - val_auc: 0.8484 - val_loss: 0.5121 - learning_rate: 0.0010
Epoch 2/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.7282 - auc: 0.8298 - loss: 0.5493 - val_accuracy: 0.7671 - val_auc: 0.8486 - val_loss: 0.5089 - learning_rate: 0.0010
Epoch 3/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7464 - auc: 0.8361 - loss: 0.5344 - val_accuracy: 0.7573 - val_auc: 0.8512 - val_loss: 0.5201 - learning_rate: 0.0010
Epoch 4/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7416 - auc: 0.8402 - loss: 0.5304 - val_accuracy: 0.7689 - val_auc: 0.8481 - val_loss: 0.5032 - learning_rate: 0.0010
Epoch 5/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7471 - auc: 0.8445 - loss: 0.5236 - val_accuracy: 0.7564 - val_auc: 0.8512 - val_loss: 0.5346 - learning_rate: 0.0010
Epoch 6/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7507 - auc: 0.8460 - loss: 0.5201 - val_accuracy: 0.7644 - val_auc: 0.8495 - val_loss: 0.5169 - learning_rate: 0.0010
Epoch 7/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7484 - auc: 0.8446 - loss: 0.5204 - val_accuracy: 0.7564 - val_auc: 0.8489 - val_loss: 0.5283 - learning_rate: 0.0010
Epoch 8/150
124/141 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7380 - auc: 0.8456 - loss: 0.5204
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7467 - auc: 0.8502 - loss: 0.5113 - val_accuracy: 0.7573 - val_auc: 0.8463 - val_loss: 0.5264 - learning_rate: 0.0010
Epoch 9/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7542 - auc: 0.8499 - loss: 0.5121 - val_accuracy: 0.7644 - val_auc: 0.8483 - val_loss: 0.5177 - learning_rate: 5.0000e-04
Epoch 10/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7562 - auc: 0.8526 - loss: 0.5086 - val_accuracy: 0.7600 - val_auc: 0.8479 - val_loss: 0.5278 - learning_rate: 5.0000e-04
Epoch 11/150
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7587 - auc: 0.8521 - loss: 0.5091 - val_accuracy: 0.7573 - val_auc: 0.8484 - val_loss: 0.5166 - learning_rate: 5.0000e-04
Epoch 12/150
133/141 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7517 - auc: 0.8526 - loss: 0.5033
Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
141/141 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7567 - auc: 0.8542 - loss: 0.5057 - val_accuracy: 0.7449 - val_auc: 0.8458 - val_loss: 0.5347 - learning_rate: 5.0000e-04

In [523]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=['No Churn', 'Churn']))

Accuracy: 0.7434257285003554
              precision    recall  f1-score   support

    No Churn       0.87      0.77      0.81      1033
       Churn       0.51      0.67      0.58       374

    accuracy                           0.74      1407
   macro avg       0.69      0.72      0.70      1407
weighted avg       0.77      0.74      0.75      1407